#!/bin/bash

if ! [ -t 0 ]; then
  read -a ref
fi
IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ "$branch" == "master" ]; then
  curl -I http://chelsea:chelsea@jenkins:8080/job/anime-microservice/buildWithParameters?token=pfa&IMAGE_NAME=anime-microservice

  if [ $? -eq 0 ] ; then
    echo "******** Ok"
  else
    echo "******** Error"
  fi
fi
